#!/usr/bin/env python
import os, sys
DATADIR = os.path.normpath(os.path.abspath(os.path.dirname(sys.argv[0]))+'/../') + '/'
sys.path.append(DATADIR)
sys.path.append(DATADIR+'/grafity/thirdparty/')

from qt import QSplashScreen, QPixmap, QApplication

class GrafitSplash(QSplashScreen):
    def __init__(self, pixmap):
        QSplashScreen.__init__(self, pixmap)

    def drawContents(self, painter):
        QSplashScreen.drawContents(self, painter)
        font = painter.font()
        font.setPointSize(11)
        text = 'r'+REVISION
        painter.drawText(418, 100, text, len(text))


app = QApplication(sys.argv)
splash = GrafitSplash(QPixmap(DATADIR + '/data/images/logos/grafit.png'))
splash.show()
from qmain import MainWindow
mainwin = MainWindow()
splash.finish(mainwin)
app.setMainWidget(mainwin)
mainwin.show()
app.exec_loop()
