#!/usr/bin/env python
import os, sys
DATADIR = os.path.normpath(os.path.abspath(os.path.dirname(sys.argv[0]))+'/../') + '/'
sys.path.append(DATADIR)
sys.path.append(DATADIR+'/grafit/thirdparty/')
import mgrafit
mgrafit.main()
